import = [
  "~/.config/alacritty/themes/themes/poimandres.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15
dimensions = { columns = 180, lines = 50}
position = { x = 150, y = 180 }

decorations = "Buttonless"

opacity = 1
# blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 15

[cursor]
style = { shape = "Beam", blinking = "Always" }
